### ISSUE TITLE
Consider replacing text labels with binary to avoid errors

### ISSUE THREAD

**Issue by SimonAB** [MwangaEP/Funestus-age#5]
For example, for XGBoost, the following error is thrown:
> ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1], got ['1-9' '10-16']

https://github.com/MwangaEP/Funestus-age/blob/dccececdf6421ae2b528f6bd39d943b39707a6a5/Code/standard_ml_fun_age_publication_fullwn.py#L245

**Comment by MwangaEP** [comment]
@SimonAB, were you able to troubleshoot this?

**Comment by SimonAB** [comment]
I haven't tried again... if it's working for you, might as well go ahead (just remember to indicate the version of XGB you are using.
